name: Grant Application
description: Submit a grant application
title: "Grant Application"
labels: ["Grant Application"]
assignees:
  - desertrat10
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this grant application! Please make sure you follow the guidelines [detailed in our docs](https://docs.unlock-protocol.com/governance/grants-bounties/).
        Once submitted, the Unlock community will review your application so please make sure it is thorough and detailed.
  - type: input
    id: title
    attributes:
      label: Title of your grant application
      description: Please enter the title of your grant application
      placeholder: ex. a plugin for Squarespace
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Description
      description: Please provide us with a complete description of your grant. You can use markdown syntax.
      placeholder: ex. I will build a plugin for Squarespace that lets website owners in squarespace token gate some of their pages. The plugin will... etc
    validations:
      required: true
  - type: input
    id: discord 
    attributes:
      label: Discord handle
      description: Your discord handle (make sure you join the [Unlock Discord server](https://discord.unlock-protocol.com/))
    validations:
      required: true
  - type: checkboxes
    id: open-source
    attributes:
      label: Is your work Open Source
      description: Do you intend to release your work as Open Source
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
- type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
