[build]
  base = "."
  command = "yarn workspace @unlock-protocol/paywall-app deploy"
  publish = "paywall-app/out"

[context.production]
  publish = "paywall-app/out"

[context.deploy-preview]
  publish = "paywall-app/out"

[build.environment]
  # We do not use the next plugin and deploy as static files!
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/"
  to = "https://docs.unlock-protocol.com/tools/paywall/"
  status = "301"
  force = true

[[redirects]]
  from = "/static/unlock.1.0.min.js"
  to = "/static/unlock.latest.min.js"
  status = "200"
  force = true

